todo_replica/models.py
import datetime

from flask_login import UserMixin
from werkzeug import generate_password_hash, check_password_hash
from sqlalchemy.ext.hybrid import hybrid_property

from .extensions import db


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(50), unique=True)
    _password = db.Column(db.String(128))
    active = db.Column(db.Boolean(), default=1)
    created_at = db.Column(db.DateTime(), default=datetime.datetime.utcnow)
    last_updated_at = db.Column(db.DateTime(), default=datetime.datetime.utcnow)

    tasks = db.relationship(
        'Task',
        foreign_keys='Task.user_id',
        backref='owner',
        lazy=True)
    
    @hybrid_property
    def password(self):
        return self._password
    
    @password.setter
    def password(self, plain_pass):
        self._password = generate_password_hash(plain_pass)
        
    def is_correct_password(self, plain_pass):
        return check_password_hash(self._password, plain_pass)


class Task(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    description = db.Column(db.Text)
    completed = db.Column(db.Boolean(), default=False)
    user_id = db.Column(db.Integer(), db.ForeignKey('user.id'))
    created_at = db.Column(db.DateTime(), default=datetime.datetime.utcnow)
    last_updated_at = db.Column(db.DateTime(), default=datetime.datetime.utcnow)

todo_replica/forms.py
from flask_wtf import FlaskForm
from wtforms import TextField, PasswordField, SubmitField
from wtforms.validators import Required, Length, EqualTo


class LoginForm(FlaskForm):
    username = TextField('Username', validators=[
        Length(min=5, max=50),
        Required()])
    password = PasswordField('Password', validators=[
        Length(min=6, max=100),
        Required()])
    submit = SubmitField('Login')


class RegisterForm(FlaskForm):
    username = TextField('Username', validators=[
        Length(min=5, max=50),
        Required()])
    password = PasswordField('Password', validators=[
        Length(min=6, max=100),
        Required(),
        EqualTo('confirm_password', message="Passwords must match.")])
    confirm_password = PasswordField('Confirm Password', validators=[
        Length(min=6, max=100),
        Required()])
    submit = SubmitField('Register')


class TaskForm(FlaskForm):
    description = TextField('Description', validators=[
        Required()])
    submit = SubmitField('Create')

todo_replica/__init__.py
from flask import Flask

from .routes.tasks import tasks
from .routes.auth import auth
from .extensions import db, toolbar, login_manager
from .commands import create_tables


def create_app(config_file='settings.py'):
    app = Flask(__name__)
    
    app.config.from_pyfile(config_file)
    
    # Register the extensions
    db.init_app(app)
    toolbar.init_app(app)
    login_manager.init_app(app)
    
    from todo_replica.models import User

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(user_id)
    
    # Register the blueprints
    app.register_blueprint(tasks)
    app.register_blueprint(auth)
    
    # Register the commands
    app.cli.add_command(create_tables)

    return app

todo_replica/routes/auth.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import login_required, logout_user, login_user, current_user

from todo_replica.extensions import db
from todo_replica.models import User
from todo_replica.forms import LoginForm, RegisterForm


auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('tasks.pending'))
    
    form = LoginForm()
    
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        
        if user and user.is_correct_password(form.password.data):
            login_user(user)
            
            return redirect(url_for('tasks.pending'))
        
    return render_template('auth/login.html', form=form)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    
    return redirect(url_for('auth.login'))


@auth.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    
    if form.validate_on_submit():
        user = User(username=form.username.data, password=form.password.data)
        
        db.session.add(user)
        db.session.commit()
        
        return redirect(url_for('auth.login'))
    
    return render_template('auth/register.html', form=form)

todo_replica/routes/main.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import login_required, current_user

from todo_replica.extensions import db
from todo_replica.models import Task
from todo_replica.forms import TaskForm


main = Blueprint('main', __name__)


@main.route('/')
@login_required
def index():
    tasks = Task.query.filter_by(user_id=current_user.get_id()).all()
    
    return render_template('main/index.html', tasks=tasks)


@main.route('/task/new', methods=['GET', 'POST'])
@login_required
def create_task():
    form = TaskForm()
    
    if form.validate_on_submit():
        task = Task(description=form.description.data)
        
        db.session.add(task)
        db.session.commit()
    
        return redirect(url_for('main.index'))
    
    return render_template('main/create.html')

todo_replica/routes/tasks.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import login_required, current_user

from todo_replica.extensions import db
from todo_replica.models import Task
from todo_replica.forms import TaskForm


tasks = Blueprint('tasks', __name__)


@tasks.route('/')
@login_required
def pending():
    tasks = Task.query.filter_by(user_id=current_user.get_id(), completed=False).all()
    
    return render_template('tasks/pending.html', tasks=tasks)


@tasks.route('/done')
@login_required
def done():
    tasks = Task.query.filter_by(user_id=current_user.get_id(), completed=True).all()
    
    return render_template('tasks/done.html', tasks=tasks)


@tasks.route('/complete/<int:task_id>')
@login_required
def complete(task_id):
    task = Task.query.get_or_404(task_id)
    
    task.completed = True
    
    db.session.commit()
    
    return redirect(url_for('tasks.pending'))


@tasks.route('/uncomplete/<int:task_id>')
@login_required
def uncomplete(task_id):
    task = Task.query.get_or_404(task_id)
    
    task.completed = False
    
    db.session.commit()
    
    return redirect(url_for('tasks.done'))


@tasks.route('/task/new', methods=['GET', 'POST'])
@login_required
def create():
    form = TaskForm()
    
    if form.validate_on_submit():
        task = Task(description=form.description.data, user_id=current_user.get_id())
        
        db.session.add(task)
        db.session.commit()
    
        return redirect(url_for('tasks.pending'))
    
    return render_template('tasks/create.html', form=form)

todo_replica/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Just another TODO app created with Flask">
    <meta name="author" content="Amador Cuenca">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>TODO Replica</title>

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/4.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link href="{{ url_for('static', filename='style.css') }}" rel="stylesheet">
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="{{ url_for('tasks.pending') }}">TODO Replica</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
            aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
                
            </ul>
            <ul class="navbar-nav">
                {% if current_user.is_authenticated %}
                <li class="nav-item"><a href="{{ url_for('tasks.create') }}" class="nav-link">New Task</a></li>
                <li class="nav-item"><a href="{{ url_for('tasks.pending') }}" class="nav-link">Pending Tasks</a></li>
                <li class="nav-item"><a href="{{ url_for('tasks.done') }}" class="nav-link">Done Tasks</a></li>
                <li class="nav-item"><a href="{{ url_for('auth.logout') }}" class="nav-link">Logout</a></li>
                {% endif %}
                
                {% if not current_user.is_authenticated %}
                <li class="nav-item active"></li><a class="nav-link" href="{{ url_for('auth.login') }}">Login <span class="sr-only">(current)</span></a></li>
                <li class="nav-item active"></li><a class="nav-link" href="{{ url_for('auth.register') }}">Register</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <main role="main" class="container">
    {% block content %}{% endblock content %}
    </main><!-- /.container -->

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="/docs/4.3/assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="https://getbootstrap.com/docs/4.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o"
        crossorigin="anonymous"></script>
</body>

</html>

todo_replica/templates/tasks/create.html
{% extends "base.html" %}

{% block content %}

<div class="row-fluid">
    <div class="col-lg-4">
        <form action="{{ url_for('tasks.create') }}" method="POST">
            {{ form.csrf_token }}
            <div class="form-group">
                {{ form.description.label }}
                {{ form.description(class="form-control") }}
            </div>
            <div class="form-group">
                {{ form.submit(class="btn btn-primary") }}
            </div>
        </form>
    </div>
</div>
{% endblock content %}

todo_replica/templates/tasks/done.html
{% extends "base.html" %}


{% block content %}
<div>
    {% if tasks %}
    <table class="table">
        <thead>
            <th scope="col">Task</th>
            <th scope="col"></th>
        </thead>
        <tbody>
        {% for task in tasks %}
            <tr>
                <td>{{ task.description }}</td>
                <td><a href="{{ url_for('tasks.uncomplete', task_id=task.id) }}"><img src="{{ url_for('static', filename='delete.png') }}" alt="Uncomplete task #{{ task.id }}"></a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% else %}
    <h2>There are not completed tasks right now...</h2>
    {% endif %}
</div>
{% endblock content %}

todo_replica/templates/tasks/index.html
{% extends "base.html" %}


{% block content %}
<div>
    <h1>TODO Replica</h1>

    {% if tasks %}
    <ul>
    {% for task in tasks %}
        <li>{{ task.description }}</li>
    {% endfor %}
    </ul>
    {% endif %}
</div>
{% endblock content %}

todo_replica/templates/tasks/pending.html
{% extends "base.html" %}


{% block content %}
<div>
    {% if tasks %}
    <table class="table">
        <thead>
            <th scope="col">Task</th>
            <th scope="col"></th>
        </thead>
        <tbody>
        {% for task in tasks %}
            <tr>
                <td>{{ task.description }}</td>
                <td><a href="{{ url_for('tasks.complete', task_id=task.id) }}"><img src="{{ url_for('static', filename='delete.png') }}" alt="Complete task #{{ task.id }}"></a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% else %}
    <h2>There are not pending tasks right now...</h2>
    {% endif %}
</div>
{% endblock content %}